print ('hello!')
#simple input
x = int(input('Enter 1st num: '))
y = int(input('Enter 2nd num: '))
z = int(input('Enter 3rd num: '))
print ('Enetered nums is: x =',x,', y =',y,', z =',z)
a = input ('Enter 1st string: ')
b = input ('Enter 2nd string: ')
print ('Enetered strings is:\na: ',a, ';\nb:',b)
#arithmetic operations
print ('arithmetic operations')
print ('x+y+z =',x+y+z)
print ('x-y+z =',x-y+z)
print ('x*(y+z) =',x*(y+z))
print ('x-y*z =',x-y*z)
print ('x/y+z =',x/y+z)
print ('x/(y-z) =',x/(y-z))
print ('x^y =',x**y)
print ('x^(y/z) =',x**(y/z))
print ('x//y =',x//y)
print ('y%z =',y%z)
#string operations
print (a+','+b)
print (a*x)
print (b*(z-y))
